- awsconfigrules/build.f/particles-awsconfigrules/config/default.js
- awsconfigrules/build.f/particles-awsconfigrules/particles/cftemplates/template.json.hbs
- awsconfigrules/build.f/particles-awsconfigrules/particles/outputs/enable_rules_lambda_arn.hbs
- awsconfigrules/build.f/particles-awsconfigrules/particles/outputs/enable_rules_lambda_name.hbs
- awsconfigrules/build.f/particles-awsconfigrules/particles/outputs/fetch_rules_lambda_arn.hbs
- awsconfigrules/build.f/particles-awsconfigrules/particles/outputs/fetch_rules_lambda_name.hbs
- awsconfigrules/build.f/particles-awsconfigrules/particles/resources/enable_rules_lambda.json.hbs
- awsconfigrules/build.f/particles-awsconfigrules/particles/resources/fetch_rules_lambda.json.hbs
- awsconfigrules/build.f/run_update_code.js
- awsconfigrules/index_enable_rules.js
- awsconfigrules/index_fetch_rules.js
- lib/aws/awsconfig.js
> Enable pre-config rules

- awsconfigrules/build.f/particles-awsconfigrules/particles/cftemplates/template.json.hbs
- awsconfigrules/build.f/particles-awsconfigrules/particles/outputs/sg_portrange_lambda_arn.hbs
- awsconfigrules/build.f/particles-awsconfigrules/particles/outputs/sg_portrange_lambda_name.hbs
- awsconfigrules/build.f/particles-awsconfigrules/particles/resources/sg_portrange_lambda.json.hbs
- awsconfigrules/build.f/run_update_code.js
- awsconfigrules/index_security_group_checker.js
- awsconfigrules/index_sg_portrange_checker.js
- lib/aws/awsconfig.js
- lib/aws/ec2.js
- lib/aws/sg-range.js
This rule would check for security group rules for all vpcs in a region and would send a non-compliant status if found rules
> Having a config rule for all vpcs in a region

- Makefile
- deploy.sh
Modified deploy script and Makefile to deploy all POC aws services.
> Modified deploy script and Makefile to deploy all POC aws services.

- CHANGELOG.md
Added blank lines to fix formatting
> CHANGELOG update, fix typo

- managed-vpc/Makefile
- managed-vpc/build.f/particles-initial/particles/cftemplates/internet_gateway.json.hbs
- managed-vpc/build.f/particles-initial/particles/resources/internet_gateway.hbs
- managed-vpc/build.f/particles-initial/particles/sets/managedvpc/internet_gateway.hbs
MA-365: Added Internet Gateway Particles.
> Managedvpc/internet gateway/ma 365

- managed-volume/Makefile
- managed-volume/build.f/particles-managed-volume/particles/sets/ebs_volume.hbs
Added Volume ID and Moutpoint Outputs to create ebs volume particles.
> Added Outputs to create ebs volume particles

- managed-vpc/build.f/particles-initial/package.json
- managed-vpc/build.f/particles-initial/particles/cftemplates/nat_gateway.json.hbs
- managed-vpc/build.f/particles-initial/particles/resources/eip.hbs
- managed-vpc/build.f/particles-initial/particles/resources/nat_gateway.hbs
- managed-vpc/build.f/particles-initial/particles/sets/managedvpc/nat_gateway.hbs
- managed-vpc/build.f/particles-initial/particles/sets/managedvpc/route_table.hbs
- managed-vpc/package.json
MA-626: Added Nat Gateway Particle.
> MA-626: Added Nat Gateway Particle.

- awscfn-stack-launcher/index_cfn_launcher.js
This code is commented as the policy is applied for the entire account and not vpc level and hence should not be deleted
> Modified the code to comment the deletePolicy

- managed-vpc/build.f/particles-initial/particles/cftemplates/nat_gateway.json.hbs
MA-626: Removed tags from  Nat Gateway Particle.
> MA-626: Removed tags from  Nat Gateway Particle.

- awsconfigrules/package.json
Fixing package.js to include mysql and node-uuid dependencied
> CE-275-awsconfigrules-ec2-create-update-trigger-lambda - Fixing package.js

- awsconfigrules/build.f/particles-awsconfigrules/package.json
- awsconfigrules/build.f/particles-awsconfigrules/particles/resources/lambda_execution_role.hbs
- awsconfigrules/index_ec2_create_trigger_db_update.js
- awsconfigrules/package.json
Included dependency packages in packages.json and added IAM policies to Rule
> Included dependency packages in packages.json and added IAM policies to Rule

- managed-os/build.f/particles-managed-os/particles/cftemplates/template.json.hbs
- managed-os/build.f/particles-managed-os/particles/conditions/is32BitOs.hbs
- managed-os/build.f/particles-managed-os/particles/conditions/is64BitOs.hbs
- managed-os/build.f/particles-managed-os/particles/partials/cf_init.hbs
- managed-os/build.f/particles-managed-os/particles/partials/linux_user_data.hbs
- managed-os/build.f/particles-managed-os/particles/resources/instance.hbs
- managed-os/build.f/particles-managed-os/particles/resources/linux_instance.hbs
- managed-os/build.f/particles-managed-os/particles/sets/parameters.hbs
**Purpose:**   Make more generic managedos CFN (remove hardcoded value from cfn)
**Changes:**  Remove hardcoded value from cfn and install opsware agent based on condition
**Integration testing/functional testing:**
1) VM should be provision with with all os type (windows-64bit ,windows-32bit,redhat)
2) Latest version of opsware agent should be installed on each type vm
3) VM should be registered hpsa
4) HPO work flow should be successfully execute
**Unit Testing**
Not Available
> MA-1502(846): Make more generic managedos CFN (remove hardcoded value from cfn)

- awsconfigrules/index_ec2_create_trigger_db_update.js
Purpose: Require changes in migration lambda functions for assume role based on one another lambda("SungardAS-Federation")
‌
For more details Please refer this link : https://mountdiablo.jira.com/browse/MA-252?filter=-1
Changes:  Particles
‌ 
Integration testing/functional testing:
Require to test migration functionality
‌
Unit Testing
Not Required
ES Lint:
Implelemted
> MA-1674: Require changes in migration lambda functions for assume role based on one another lambda("SungardAS-Federation")

- awscfn-stack-launcher/Makefile
- awscfn-stack-launcher/build.f/particles-awscfn-stack-launcher/config/default.js
- awsconfig/Makefile
- awsconfig/build.f/particles-awsconfig/config/default.js
- awsconfigrules/build.f/particles-awsconfigrules/package.json
- cloudtrail/Makefile
- cloudtrail/build.f/particles-cloudtrail/config/default.js
- deploy.sh
- managed-elb/Makefile
- managed-elb/build.f/particles-initial/config/default.js
- managed-volume/Makefile
- managed-volume/build.f/particles-managed-volume/config/default.js
- particle-region-mapping
Purpose:  Deployment of Microservices in DR Region
For more details Please refer this link : https://mountdiablo.jira.com/browse/MA-2687
Changes:  Particles
‌
Unit Testing
NA
ES Lint:
NA
> MA- 2687:  Deployment of Microservices in DR Region

- particle-region-mapping
Purpose: Need to modify a file in aws services for remove deployment of federation in us-west-2 region
For more details Please refer this link : https://mountdiablo.jira.com/browse/MA-2847
Changes: Particles
‌
Unit Testing
NA
ES Lint:
NA
> MA-Need to modify a file in aws services for remove deployment of federation in us-west-2 region

- managed-os/build.f/particles-managed-os/particles/partials/cf_init.hbs
- managed-os/build.f/particles-managed-os/particles/partials/linux_user_data.hbs
Updated HPSA S3 URL to download HPSA Agents.
> MA-2872: Updated S3 URL for HPSA Agents

- managed-os/build.f/particles-managed-os/particles/partials/linux_user_data.hbs
MA-2886: Updated HPSA S3 URL for Linux.
> MA-2886: Updated HPSA S3 URL for Linux

- managed-vpc/build.f/particles-initial/particles/sets/managedvpc/vpngateway.hbs
modified vpngateway.hbs to set ActiveTransitVpcSpoke tag key dynamically while creating new managed VPC ( through managedVpc sails API )for active transit Vpc.
> MA-2958 / API - modify Managed VPC workflow to tag VGW(s) with specific tag

- managed-vpc/build.f/particles-initial/particles/sets/managedvpc/vpngateway.hbs
Reverts SungardAS/aws-services#117
> Revert "MA-2958 / API - modify Managed VPC workflow to tag VGW(s) with specific tag"

- managed-vpc/build.f/particles-initial/particles/sets/managedvpc/vpngateway.hbs
MA-3681:Updated VGW to take BGP ASN value as parameter.
> MA-3681:Updated VGW to take BGP ASN value as parameter.

- particle-region-mapping
MA-3681:Updated particle region mapping file.
> MA-3681:Updated particle region mapping file.
